### PR TITLE
propose a few spelling corrections and tab removals

### PR DESCRIPTION
**Pull request by jeis2497052**
I propose a couple of spelling corrections with this commit

### CODE REVIEW

**Comment by luisrudge** [comment]
Hi, thanks for the PR. The docs are auto generated based on the comments in the code, so any changes made to the html files will be overridden in the next build of the documentation. Can you fix the spelling mistakes in the code comments? 🎉

**Comment by jeis2497052** [comment]
I did update popup.js and db-connection.js as well.  Are those changes OK ?

**Comment by luisrudge** [comment]
Yeah, you can leave only the .js changes

**Comment by jeis2497052** [comment]
OK, so revert the html changes before this commit will pass the review ?  Create a new PR with just js proposed spelling corrections ?

thanks.

**Comment by luisrudge** [comment]
You can revert the changes in the html file or start over, whatever is easier to you

**Comment by luisrudge** [comment]
I'll update docs in another commit

**Pull request closed without merging**
