### PR TITLE
Remove global from window helpers

### PR DESCRIPTION
**Pull request by fetis**
Hello,

* I removed `global` from window helpers to make it Angular 6 compatible.
* Also, configured webpack to prevent issue `global` in the future (it does it automatically when encounters this variable).
* And some minor code cleanup.

I left current testing approach intact (manually mock `window` object). I think in the future it can be replaced with [JSDOM](https://github.com/jsdom/jsdom) or similar implementation

Related issues #759 #755 #754 #753 #748

### CODE REVIEW

**Comment by luisrudge** [comment]
Thanks for the PR. Do you know why this line lost coverage? https://codecov.io/gh/auth0/auth0.js/compare/5a531f5013e77b0185e645954e5b505ab61b16db...2966805bd0100ede52a9aef1e81dd21ba5347d68/changes

**Comment by fetis** [comment]
I assume it's because of this change https://github.com/auth0/auth0.js/pull/764/files#diff-fa3d40d414115b7a8cf9ef99f7282b22R173, which I took as someone accidentally duplicated the line.s

But I think it should be restored in a more explicit way, because popup_handler may return the current instance

**Comment by luisrudge** [comment]
ahaha, yeah.. good catch! That's probably it, considering it's testing `should open the window once`

**Comment by fetis** [comment]
I've fixed it. Show go back to normal now.

**Comment by luisrudge** [comment]
Thanks for the PR! 🎉

**Comment by fetis** [comment]
thanks for merge

**Comment by luisrudge** [comment]
This was already released in 9.6.1 🎉

**Pull request merged**
