### PR TITLE
Set up initial Renovate configuration

### PR DESCRIPTION
**Pull request by ScottRudiger**
Questions/Next steps incoming. 🚀

### CODE REVIEW

**Comment by ScottRudiger** [comment]
Questions/Next steps incoming. 🚀

**Comment by luisrudge** [comment]
hey, sorry to make you spend some time with this. We already have snyk.io monitoring our repos and our IT team said they don't want another tool to do the same thing 😬 

I'll close this out and make sure we make security dependency updates more often. Thanks for the help!

**Comment by ScottRudiger** [comment]
No worries; this will be here for the future in case they decide a change is warranted. 😃

**Comment by ScottRudiger** [comment]
@luisrudge I looked into snyk.io a little and it seems like it'd do a good job of catching vulnerable dependencies.

However, I noticed there haven't been any Snyk PRs yet (and it didn't catch the deps I updated in #892). Were [automatic pull requests disabled](https://snyk.io/docs/github/#disable-automatic-pull-requests)? If so, enabling them should go a long way in keeping things secure without much hassle. 👍

**Pull request closed without merging**
