### PR TITLE
Bump superagent to 5+

### PR DESCRIPTION
**Pull request by jsoref**
### Changes

Updates superagent to 5+

### References

#1041

### Testing

Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors. 

### Checklist

[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)

[x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

[x] All tests and linters described in the [Develop section](https://github.com/auth0/auth0.js#develop) run without errors

### CODE REVIEW

**Comment by jsoref** [comment]
@lbalmaceda : I'll look, but please be aware that the I followed the instructions in https://github.com/auth0/auth0.js#develop which made no reference to `yarn` (especially not `yarn test:es-check:es5 && yarn test:es-check:es2015:module`) -- If that's important, then perhaps someone (I'm happy to do it if someone provides the instructions) should update the instructions...

**Comment by jsoref** [comment]
fwiw, I just checked out master (w/o my change) and I get the same failure:
```
user:        Steve Hobbs <steve.hobbs.mail@gmail.com>
date:        Tue Sep 10 11:36:16 2019 +0100
summary:     Merge pull request #1039 from Nyholm/patch-1
```
```sh
$ rm -rf node_modules/; yarn install && yarn test:es-check:es5 && yarn test:es-check:es2015:module
yarn install v1.16.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "eslint > espree > acorn-jsx@5.0.1" has incorrect peer dependency "acorn@^6.0.0".
warning " > eslint-config-auth0-base@13.1.0" has incorrect peer dependency "eslint@^3.19.0 || ^4.3.0".
warning "eslint-config-auth0-base > eslint-config-airbnb-base@11.3.2" has incorrect peer dependency "eslint@^3.19.0 || ^4.5.0".
[4/4] 🔨  Building fresh packages...
✨  Done in 7.47s.
yarn run v1.16.0
$ es-check es5 'dist/!(*.esm)*.js'
ES-Check: there were 1 ES version matching errors.

          ES-Check Error:
          ----
          · erroring file: dist/auth0.js
          · error: SyntaxError: The keyword 'const' is reserved (1103:8)
          · see the printed err.stack below for context
          ----

          SyntaxError: The keyword 'const' is reserved (1103:8)
    at Parser.pp$4.raise (auth0.js/node_modules/es-check/node_modules/acorn/dist/acorn.js:2769:13)
    at Parser.pp$3.checkUnreserved (auth0.js/node_modules/es-check/node_modules/acorn/dist/acorn.js:2699:10)
    at Parser.pp$3.parseIdent (auth0.js/node_modules/es-check/node_modules/acorn/dist/acorn.js:2728:24)
    at Parser.pp$3.parseExprAtom (auth0.js/node_modules/es-check/node_modules/acorn/dist/acorn.js:2164:19)
    at Parser.pp$3.parseExprSubscripts (auth0.js/node_modules/es-check/node_modules/acorn/dist/acorn.js:2074:19)
    at Parser.pp$3.parseMaybeUnary (auth0.js/node_modules/es-check/node_modules/acorn/dist/acorn.js:2051:17)
    at Parser.pp$3.parseExprOps (auth0.js/node_modules/es-check/node_modules/acorn/dist/acorn.js:1993:19)
    at Parser.pp$3.parseMaybeConditional (auth0.js/node_modules/es-check/node_modules/acorn/dist/acorn.js:1976:19)
    at Parser.pp$3.parseMaybeAssign (auth0.js/node_modules/es-check/node_modules/acorn/dist/acorn.js:1951:19)
    at Parser.pp$3.parseExpression (auth0.js/node_modules/es-check/node_modules/acorn/dist/acorn.js:1916:19)
    at Parser.pp$1.parseForStatement (auth0.js/node_modules/es-check/node_modules/acorn/dist/acorn.js:938:19)
    at Parser.pp$1.parseStatement (auth0.js/node_modules/es-check/node_modules/acorn/dist/acorn.js:806:32)
    at Parser.pp$1.parseBlock (auth0.js/node_modules/es-check/node_modules/acorn/dist/acorn.js:1144:23)
    at Parser.pp$3.parseFunctionBody (auth0.js/node_modules/es-check/node_modules/acorn/dist/acorn.js:2614:22)
    at Parser.pp$1.parseFunction (auth0.js/node_modules/es-check/node_modules/acorn/dist/acorn.js:1248:8)
    at Parser.pp$1.parseFunctionStatement (auth0.js/node_modules/es-check/node_modules/acorn/dist/acorn.js:957:15)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I have no idea what's up with this. (I've already lost a week hunting down this bug, I don't look forward to spending another week figuring out why `es-check` doesn't approve of `const`.)

**Comment by jsoref** [comment]
#1043 is my attempt to document how to contribute...

**Comment by jsoref** [comment]
@lbalmaceda: as superagent switched to es6, the solution appears to be to use babel to generate es5 code, with that, the tests now pass.

**Comment by jsoref** [comment]
@luisrudge : 5 seems to work. I'm not picky, if you'll take 5, that should be fine w/ us.

**Comment by luisrudge** [comment]
perfect @jsoref. Did you check superagent for any breaking changes? I skimmer through the docs and didn't see any breaking changes (apart from the final bundle) 🤔

**Comment by jsoref** [comment]
> superagent@4.0.0: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.

Is the one change I know of. I'm not sure if Auth0 cares.

**Comment by luisrudge** [comment]
No, I think that's fine. I'll test this before merging to make sure everything works and that the bundle size is about the same. Thanks for the PR 🎉

**Comment by luisrudge** [comment]
Hi again @jsoref 👋 I just tested this locally and [this](https://github.com/auth0/auth0.js/blob/master/src/helper/request-builder.js#L58-L61) code path is now failing. Apparently, the `end` method is not chainable anymore. Would you mind checking if I did something wrong? We can't migrate to promises without a breaking change 😬

**Comment by jsoref** [comment]
@luisrudge : Modern promises use `.then` instead of `.end`, see: https://visionmedia.github.io/superagent/

If you can give me instructions for how to test, I can probably provide a commit...

**Comment by luisrudge** [comment]
@jsoref we can't migrate to promises yet. We have to keep using the callback approach for now. You can test this by:

- cloning this repo
- `yarn install`
- `yarn start`
- This will open the browser in a test page
- Click the first 'login' button

You'll see something like this:
image

**Comment by jsoref** [comment]
This isn't quite right, but it's along the lines of something that could be done...

**Comment by stevehobbsdev** [comment]
Hey @jsoref, just checking on the status of this; is it something you still have interest on working on? Currently the tests are stil failing.

**Comment by stevehobbsdev** [comment]
Closing this PR for now due to inactivity. If this is still an on-going process, feel free to reopen.

**Pull request closed without merging**
