### PR TITLE
Update cdn uploader tool to v1.3.0

### PR DESCRIPTION
**Pull request by ramasilveyra**

### CODE REVIEW

**Comment by luisrudge** [comment]
hey.. sorry man. we had to do some git black magic to cut a release. can you send this PR again? Thanks 🎉

**Comment by ramasilveyra** [comment]
Yes no problem, it's easy!

**Comment by hzalaz** [comment]
@luisrudge no need we can squash on merge. Thanks @ramasilveyra

**Comment by luisrudge** [comment]
It's not the squash.. it's the conflicts. it's probably easyer to just open a new one

**Pull request merged**
