### PR TITLE
Fix readme section order

### PR DESCRIPTION
**Pull request by yilinjuang**
### Changes

Doc updated.

### References

None

### Testing

Not tested.

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [ ] All tests and linters described in the [Develop section](https://github.com/auth0/auth0.js#develop) run without errors

### CODE REVIEW

**Comment by stevehobbsdev** [comment]
👋 I couldn't see the reasoning for this change in your PR description, can you elaborate?

**Comment by yilinjuang** [comment]
@stevehobbsdev the subsections `### Initialize` and `### API` belong to `## auth0.Management`, so I moved `## Passwordless Login` downwards.

**Comment by yilinjuang** [comment]
hi @stevehobbsdev does it make sense to you?

**Review by stevehobbsdev — APPROVED** [review]
It makes sense now that you've explained it! Thanks for the contribution 🎉

**Pull request merged**
