### PR TITLE
Create migration guide section in README.md

### LINKED ISSUE #857: Migration links for v8/v9 are not together in README.md
Thank you for using Auth0.js! Please read the following before creating a new issue.

- [ ] Is this a question about Auth0 in general or a support request? Get in touch with us at https://support.auth0.com.
- [x] Is this issue something you can fix? Please send us a pull request! Bug fixes are welcome.

### PR DESCRIPTION
**Pull request by puneet97**
Closes #857

### CODE REVIEW

**Comment by luisrudge** [comment]
Thanks, but this is already covered in our docs.

**Comment by puneet97** [comment]
> this is already covered in our docs.
Yeah, even the links in the PR go to the docs themselves. The PR just collects the various migration guide links, that are currently present in different places in the README, together in their own section for a clear presentation.

**Comment by puneet97** [comment]
> this is already covered in our docs.

Yeah, even the links in the PR go to the docs themselves. The PR just collects the various migration guide links, that are currently present in different places in the README, together in their own section for a clear presentation.

**Comment by puneet97** [comment]
@luisrudge I've updated the PR to current master in #869 for review.
The PR doesn't copy the docs to readme, it just creates a dedicated section for them as currently the one for v9 is in the introduction and the one for v8 is in documentation section.

**Pull request closed without merging**
