### PR TITLE
 Remove invalid params from authorize url to eliminate console warnings

### PR DESCRIPTION
**Pull request by jeremybull**
Using the `timeout` parameter with `renewAuth()` produces this warning in the console:
> Following parameters are not allowed on the `/authorize` endpoint: [timeout]

Likewise, using `tenant` and `popupOptions` with `popup.authorize()` produces this warning:
> Following parameters are not allowed on the `/authorize` endpoint: [tenant,popup_options]

These options needed to be blacklisted before the `/authorize` url is built.

### CODE REVIEW

**Comment by jeremybull** [comment]
@luisrudge is there something I should do to initiate a review on this pr? I really appreciated your quick response on my original attempt (#532): I believe this one addresses your feedback. Thanks!

**Comment by luisrudge** [comment]
Hi, sorry to keep you waiting! Can you add the popupOptions blacklist to the test as well? I think it's the only thing missing

**Comment by jeremybull** [comment]
Sorry @luisrudge I'm not following you. Could you be more specific about which test you want me to change and how? (So far I have not added or enhanced any tests with this PR.)

**Comment by luisrudge** [comment]
Sure thing! Ideally, for each method that you're now blacklisting the timeout/popupOptions/tenant properties, you should have a test that you call the method **with** those properties, and then you validate that the authorize url doesn't contain any of those properties.

**Comment by luisrudge** [comment]
fixed in https://github.com/auth0/auth0.js/pull/611

**Pull request closed without merging**
