### PR TITLE
Parse file protocol from Url

### PR DESCRIPTION
**Pull request by anion155**
When this library is used in electron, locations in most cases are files

### CODE REVIEW

**Comment by luisrudge** [comment]
Can you please add a test for that? Thanks!

**Comment by luisrudge** [comment]
ping @anion155

**Comment by anion155** [comment]
Will add. In a moment.

**Comment by anion155** [comment]
There is 'url' helper, used only once in 'web-auth/popup', shouldn't it be 'objectHelper.getOriginFromUrl'?

**Pull request merged**
