### PR TITLE
fix localStorage security error on ios

### PR DESCRIPTION
**Pull request by hwestbrook**
This fixes https://github.com/auth0/auth0.js/issues/477

### CODE REVIEW

**Comment by luisrudge** [comment]
Hi @hwestbrook. Thanks for the PR! Do you mind adding a test to [this](https://github.com/auth0/auth0.js/blob/master/test/helper/storage-handler.test.js) file? I'll merge when it's ready. 🎉

**Comment by AVVS** [comment]
Some notes on the PR based on #570

1. Try to use `sessionStorage` is possible
2. Verify that you can actually use it, because it will throw QuotaError during certain conditions

```js
var storage;
var $w = windowHandler.getWindow();

try {
  storage = window.localStorage;
  storage.setItem('x', '1');
  assert(storage.getItem('x') === '1');
  storage.removeItem('x');
  this.storage = storage;
} catch (e) {
  storage = new CookieStorage();
}

this.storage = storage;
````

Last, but not the least, leverage code that already does that from folks at mozilla, while I understand its a 3rd party dependency, doing all the cases right is not as easy as it sounds ;)

**Comment by luisrudge** [comment]
1: why?
2: this is already implemented in the setItem method (if we can't write, we'll fallback to another storage)

I agree we should use a 3rd party for this. We just don't have the time to do research and migrate right now.

**Comment by AVVS** [comment]
1. since it writes down state & nonce - temporary data - you'd avoid the need to cleanup local storage
2. didnt notice, that should take care of it

**Comment by luisrudge** [comment]
1) I like that, but we use storage to save other types of data as well. Maybe we need to rethink how we handle storage from the ground up, taking in consideration short and long lived objects. We can't do it right now, though :(

**Comment by luisrudge** [comment]
I'm rebuilding the storage layer and this should go away when I get this done.

**Pull request closed without merging**
