### PR TITLE
Fix incorrect base64 decode

### PR DESCRIPTION
**Pull request by wooorm**
Fixes strings containing two or more dashes and/or underscores.

This affected some users, seemingly at random, especially with large tokens!

### CODE REVIEW

**Comment by jfromaniello** [comment]
nice catch

It seems that we have the same problem here:
https://github.com/auth0/jwt-decode/blob/master/lib/base64_url_decode.js#L4

**Comment by wooorm** [comment]
It does! I found loads more by searching GitHub for `base64_url_decode`, weird!

**Comment by wooorm** [comment]
@pose @jfromaniello Any word on this, interest in implementing?

**Comment by pose** [comment]
@wooorm Merged, please check the 6.4.1 in about an hour. Thanks again!

**Comment by wooorm** [comment]
:+1:

**Pull request merged**
