### PR TITLE
Update superagent dependency to 5.3.1 to get around babel bug

### PR DESCRIPTION
**Pull request by paviad**
Please update superagent to 5.3.1, current version (3.8.3) cannot be used in localized angular builds.

### CODE REVIEW

**Comment by stevehobbsdev** [comment]
Thanks @paviad - sorry for the radio silence, let me pick this up.

**Comment by stevehobbsdev** [comment]
I've evaluated the change but will need some internal changes, it's not just a version bump - leave it with me 👍

**Comment by paviad** [comment]
Thanks, I ended up forking the lib and making this change, it works for me.

**Comment by stevehobbsdev** [comment]
Do you get an error written to the console when doing cross-origin authentication? Login appears to work but I need to change a couple l of bits to prevent an error being surfaced.

**Pull request merged**
